### ISSUE TITLE
/etc/httpd/conf.d/wsgi.conf: file not found

### ISSUE THREAD

**Issue by porunov** [saltstack-formulas/apache-formula#163]
Hello,

I tried to install apache with mod_wsgi but got an error.

Here is the error:
```

          ID: /etc/httpd/conf.d/wsgi.conf
    Function: file.uncomment
      Result: False
     Comment: /etc/httpd/conf.d/wsgi.conf: file not found
     Started: 21:49:29.489326
    Duration: 1.944 ms
     Changes: 
```

Here is my pillar file:

```
apache:
  name_virtual_hosts:
    - interface: '*'
      port: 80

  sites:

    keystone.apache.jblur.com:
      enabled: True
      template_file: salt://apache/vhosts/standard.tmpl
      port: '8880'
```

Here is my states file:
```
include:
  - apache
  - apache.config
  - apache.mod_wsgi
```

Why does it happen?

My OS is: CentOS 7.2

Best regards,
Alexandr
