### ISSUE TITLE
Support for installing/configuring MPM's.

### ISSUE THREAD

**Issue by fintanmm** [saltstack-formulas/apache-formula#25]
Hi 

Is there a chance of supporting the installation/configuration of prefork, worker or event mpm's? Thanks

```
fintan
```

**Comment by aboe76** [comment]
see latest pull request,

**Comment by aboe76** [comment]
The TimeOut option isn't available in the config files so that one could be added like the keepalive settings which are available.

The mpm settings aren't in pillar.example: but they are available here are some example pillars:

mpm_prefork
```
apache:
  mpm:
    module: mpm_prefork
    params:
      start_servers: 2
      max_request_workers: 150
      min_spare_threads: 25
      max_spare_threads: 75
      thread_limit: 64
      threads_per_child: 25
      max_connections_per_child: 0
```

mpm_event
```
apache:
  mpm:
    module: mpm_event
    params:
      start_servers: 2
      max_request_workers: 150
      min_spare_threads: 25
      max_spare_threads: 75
      thread_limit: 64
      threads_per_child: 25
      max_connections_per_child: 0
```

mpm_worker
```
apache:
  mpm:
    module: mpm_worker
    params:
      start_servers: 2
      max_request_workers: 150
      min_spare_threads: 25
      max_spare_threads: 75
      thread_limit: 64
      threads_per_child: 25
      max_connections_per_child: 0
```
