### ISSUE TITLE
In Debian apache.config plays two opposite actions

### ISSUE THREAD

**Issue by gaetanars** [saltstack-formulas/apache-formula#285]
When I use apache or apache.config state on Debian system, each run had some modified files : 
/etc/apache2/sites-available/000-default.conf

apache.config.own_default_vhost produce
Name: /etc/apache2/sites-available/000-default.conf - Function: file.managed - Result: Changed

and apache.config.debian_full produce :
Name: /etc/apache2/sites-available/000-default.conf - Function: file.absent - Result: Changed

Have I missed some pillars to block this double change or is that a bug in this formula?

Regards

**Comment by noelmcloughlin** [comment]
I recently did a refactoring of this formula but did not add that code.

The `file.absent` state already existed in `debian_full.sls` file.  I'm not sure why.  If it is a bug and `debian_full` state is not doing anything useful - please consider raising a PR to remove that line from `apache.config.init.sls` and àpache.config.clean` files.

These are the states causing your issue. I do not know what òwn_default_vhost` and `debian_full` states are for. If they are useful then updating the README to explain why would help.  Since these are tiny PRs I hope you could contribute. thanks.
```
/etc/apache2/sites-available/{{ apache.default_site }}:
  file.absent:
    - require:
      - pkg: apache
/etc/apache2/sites-available/{{ apache.default_site_ssl }}:
  file.absent:
    - require:
      - pkg: apache
```
