### ISSUE TITLE
[FEATURE] handle multiple CustomLog directives

### ISSUE THREAD

**Issue by boileaum** [saltstack-formulas/apache-formula#386]
### Is your feature request related to a problem?

Handle multiple CustomLog directives in the same config file (see https://httpd.apache.org/docs/2.4/fr/mod/mod_log_config.html#customlog). 

### Describe the solution you'd like

The following apache config example:

```
CustomLog /var/log/apache2/access.log combined
CustomLog "|/usr/bin/logger -t apache -p local6.info" combined
```

could be translated into the pillar file as:

```yaml
apache:
  sites:
    default:
      CustomLog:
         - /var/log/apache2/access.log combined
         - "|/usr/bin/logger -t apache -p local6.info" combined
```

### Describe alternatives you've considered

A personal hack independent of this formula.
