### ISSUE TITLE
PR #45 broke default DocumentRoot

### ISSUE THREAD

**Issue by ross-p** [saltstack-formulas/apache-formula#50]
In PR #45 code was added that does not allow for the default DocumentRoot.

Thus all existing Salt states that are using the default are now broken and returning the following error:

```text
----------
          ID: www.host.com-documentroot
    Function: file.directory
        Name: None
      Result: False
     Comment: Specified file None is not an absolute path
     Started: 23:25:55.852689
    Duration: 4.705 ms
     Changes:
```

Example problem:

```yaml
{{ id }}-documentroot:
  file.directory:
    - unless: test -d {{ site.get('DocumentRoot') }}
    - name: {{ site.get('DocumentRoot') }}
```

This is contrary to the existing behavior of the virtual host templates which implements the default thusly:

```jinja2
site.get('DocumentRoot', '{0}/{1}'.format(map.wwwdir, sitename))
```

@thornycrackers please fix.

Everyone else, if you use default DocumentRoot I recommend you don't update to the latest version of this repo.  @1949ff4 is still a good version.
