### ISSUE TITLE
Question regarding `register-site` pillar

### ISSUE THREAD

**Issue by michaelforge** [saltstack-formulas/apache-formula#97]
Could you explain, what exactly needs to be provided in this block?

```
  # ``apache.debian_full`` formula additional configuration:
  register-site:
    # any name as an array index, and you can duplicate this section
    UNIQUE_VALUE_HERE:
      name: 'my name'
      path: 'salt://path/to/sites-available/conf/file'
      state: 'enabled'
```

What exactly must be contained in `salt://path/to/sites-available/conf/file`?
Isn't it being generated by `sites` block (apache.vhosts) already?
